config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'books#index'

  resources :books

  get 'search', to: 'searches#index'

	scope module: :apps do
		resource :profile, only: [:show, :edit, :update]
		resources :bookmarklists, only: [:index]
	end

	namespace :api, defaults: {format: :json} do
		scope '/books/:book_id' do
			resource :bookmark, only: [:show, :create, :destroy]
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_one_attached :eyecatch
	has_rich_text :content

	validates :title, presence: true
	validates :title, length: { minimum: 2, maximum: 100 }

  validates :content, presence: true

	belongs_to :user
	has_many :bookmarks, dependent: :destroy

	def display_created_at
    I18n.l(self.created_at, format: :default)
	end

	def bookmark_count
		bookmarks.count
	end

	def author_name
		user.display_name
	end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
	has_many :bookmarklists, through: :bookmarks, source: :book

  has_one :profile, dependent: :destroy

  def has_written?(book)
    books.exists?(id: book.id)
  end

  def has_bookmarked?(book)
    bookmarks.exists?(book_id: book.id)
  end

  def prepare_profile
    profile || build_profile
  end

	def display_name
		profile&.nickname || self.email.split('@').first
	end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end

end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
end

app/controllers/api/bookmarks_controller.rb
class Api::BookmarksController < Api::ApplicationController
	before_action :authenticate_user!
	def show
		book = Book.find(params[:book_id])
		book_status = current_user.has_bookmarked?(book)
		render json: { hasBookmarked: book_status }
	end

	def create
		book = Book.find(params[:book_id])
		book.bookmarks.create!(user_id: current_user.id)
		render json: { status: 'ok' }
	end

	def destroy
		book = Book.find(params[:book_id])
		bookmark = book.bookmarks.find_by!(user_id: current_user.id)
		bookmark.destroy!
		render json: { status: 'ok' }
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps/application_controller.rb
class Apps::ApplicationController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/apps/bookmarklists_controller.rb
class Apps::BookmarklistsController < Apps::ApplicationController
	def index
		@books = current_user.bookmarklists
	end
end

app/controllers/apps/profiles_controller.rb
class Apps::ProfilesController < Apps::ApplicationController
	def show
		@profile = current_user.profile
	end

	def edit
		@profile = current_user.prepare_profile
	end

	def update
		@profile = current_user.prepare_profile
		@profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィール更新！'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
	end

	private
	def profile_params
		params.require(:profile).permit(:nickname, :avatar)
	end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
	before_action :authenticate_user!
	def show
		book = Book.find(params[:book_id])
		book_status = current_user.has_bookmarked?(book)
		render json: { hasBookmarked: book_status }
	end

	def create
		book = Book.find(params[:book_id])
		book.bookmarks.create!(user_id: current_user.id)
		render json: { status: 'ok' }
	end

	def destroy
		book = Book.find(params[:book_id])
		bookmark = book.bookmarks.find_by!(user_id: current_user.id)
		bookmark.destroy!
		render json: { status: 'ok' }
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:show]
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@books = Book.all
	end

	def show
	end

	def new
		@book = current_user.books.build
	end

	def create
		@book = current_user.books.build(book_params)
		if @book.save
			redirect_to book_path(@book), notice: '保存できました'
		else
			flash.now[:error] = '保存に失敗しました'
			render :new
		end
	end


	def edit
		@book = current_user.books.find(params[:id])
	end

	def update
		@book = current_user.books.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book), notice: '更新できました'
		else
			flash.now[:error] = '更新できませんでした'
			render :edit
		end
	end

	def destroy
		book = current_user.books.find(params[:id])
		book.destroy!
		redirect_to root_path, notice: '削除に成功しました'
	end

	private
	def book_params
		params.require(:book).permit(:title, :content, :eyecatch)
	end

	def set_book
		@book = Book.find(params[:id])
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def show
		@profile = current_user.profile
	end

	def edit
		@profile = current_user.prepare_profile
	end

	def update
		@profile = current_user.prepare_profile
		@profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィール更新！'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
	end

	private
	def profile_params
		params.require(:profile).permit(:nickname, :avatar)
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

	def index
    @books = Book.looks(params[:search], params[:word])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/apps/bookmarklists/index.html.haml
.container
  %h2
    ブックマークリスト
  - @books.each do |book|
    = render 'commons/book', book: book

app/views/apps/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar
    %div
      = f.label :nickname, 'ハンドルネーム'
    %div
      = f.text_field :nickname, class: 'text'

    = f.submit '保存', class: 'btn-primary'

app/views/apps/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          = current_user.display_name
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path
  - current_user.books.each do |book|
    = render 'commons/book', book: book

app/views/books/_form.html.haml
.container
	%ul
		- book.errors.full_messages.each do |message|
			%li= message
	= form_with(model: book, local: true) do |f|
		%div
			= f.label :eyecatch, 'アイキャッチ'
		%div
			= f.file_field :eyecatch
		%div
			= f.label :title, 'タイトル'
		%div
			= f.text_field :title, class: 'text'
		%div
			= f.label :content, '内容'
		%div
			= f.rich_text_area :content
		= f.submit '保 存', class: 'btn-primary'

app/views/books/_form.htmll.haml
.container
	%ul
		- book.errors.full_messages.each do |message|
			%li= message
	= form_with(model: book, local: true) do |f|
		%div
			= f.label :title, 'タイトル'
		%div
			= f.text_field :title, class: 'text'
		%div
			= f.label :content, '内容'
		%div
			= f.text_area :content
		= f.submit '保存', class: 'btn-primary'

app/views/books/edit.html.haml
= render 'form', book: @book

app/views/books/index.html.haml
.container
	= render "searches/form"
	- @books.each do |book|
		= render 'commons/book', book: book
	= link_to new_book_path do
		.float_btn
			%i.fa.fa-plus

app/views/books/new.html.haml
.container
	%ul
		- @book.errors.full_messages.each do |message|
			%li= message
	= form_with(model: @book, local: true) do |f|
		%div
			= f.label :title, 'タイトル'
		%div
			= f.text_field :title, class: 'text'
		%div
			= f.label :content, '内容'
		%div
			= f.text_area :content
		= f.submit '保存', class: 'btn-primary'

app/views/books/show.html.haml
.article#book-show{data: {book_id: @book.id}}
	- if @book.eyecatch.attached?
		.article_image
			= image_tag @book.eyecatch
	%h1.article_title= @book.title
	.article_detail
		= image_tag @book.user.avatar_image
		%div
			%p= @book.author_name
			%p= @book.display_created_at
		-if user_signed_in? && current_user.has_written?(@book)
			.article_detail_actions
				.dropdown
					= image_tag 'actions.svg', class: 'dropbtn'
					.dropdown-content.mini
						= link_to '編集する', edit_book_path(@book)
						= link_to '削除する', book_path(@book), data: { method: 'delete', confirm: '本当に削除してもよろしいですか?' }
	.article_content
		= @book.content
	- if user_signed_in?
		.article_bookmark.hidden.active-bookmark
			= image_tag 'bookmark-active.svg'
		.article_bookmark.hidden.inactive-bookmark
			= image_tag 'bookmark.svg'

= javascript_pack_tag 'book'

app/views/commons/_book.html.haml
= link_to book_path(book) do
	.card
		- if book.eyecatch.attached?
			.card_image
				= image_tag book.eyecatch
		.card_content
			.card_title
				= book.title
			.card_bookmark
				= image_tag 'bookmark.svg'
				%span= book.bookmark_count
			.card_detail
				= image_tag book.user.avatar_image
				%div
					%p= book.author_name
					%p= book.display_created_at

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title BookApp
		= csrf_meta_tags
		= csp_meta_tag
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
		%link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet"}/

	%body
		%header.header
			.header_logos
				- if !current_page?(root_path)
					= link_to :back do
						= image_tag 'back.svg', class: 'header_back'
				%p.header_pageTitle
					= link_to 'BookApp', root_path
			- if user_signed_in?
				.dropdown
					= image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
					.dropdown-content
						= link_to 'プロフィール', profile_path
						= link_to 'ブックマークリスト', bookmarklists_path
						= link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
			- else
				= link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
		- if flash.present?
			.flash
				- flash.each do |key, value|
					%div{:class => key}= value
		= yield

app/views/searches/_form.html.haml
- if user_signed_in?
	.search_form
		= form_with url: search_path, local: true, method: :get do |f|
			%div
				= f.label :word, 'タイトル検索'
			%div
				= f.text_field :word, class: 'text'
			%div
				= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]])
			= f.submit '検 索', class: 'btn btn-primary position'

app/views/searches/index.html.haml
.container
  %h2
    検索結果
  - @books.each do |book|
    = render 'commons/book', book: book